site_name: Cours de NSI
theme:
  name: material
  language: fr
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.path
    - navigation.top
  plugins:
    - search
    - search.highlight
